global:
  scrape_interval: 5s
rule_files:
  - /etc/prometheus/alerts.yml
scrape_configs:
  - job_name: 'sample-node-api'
    static_configs:
      - targets: ['localhost:3000']
        labels:
          env: 'staging'
